apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress-https
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: $(VC_NAMESPACE)-$(VC_INSTANCE)-errorpage@kubernetescrd, $(VC_NAMESPACE)-$(VC_INSTANCE)-https-redirect@kubernetescrd, $(VC_NAMESPACE)-$(VC_INSTANCE)-rewrite@kubernetescrd
spec:
  tls:
    - hosts:
      - demo.virtocommerce.com
      - admin-demo.virtocommerce.com
      secretName: vc-wildcart
  rules:
  - host: demo.virtocommerce.com
    http:
      paths:
      - backend:
          serviceName: storefront
          servicePort: 80
        path: /
  - host: admin-demo.virtocommerce.com
    http:
      paths:
      - backend:
          serviceName: platform
          servicePort: 80
        path: / 